version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped
    environment:
      - APP_NAME=file_upload_execute
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
